project_id = "ezdlbipecmcykybkshkz"

[api]
enabled = true
port = 54321

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[inbucket]
port = 54324

[storage]
file_size_limit = "50MB"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/auth/callback"]

[auth.email]
enable_signup = true
enable_confirmations = true

[auth.email.template.confirmation]
subject = "Potwierdź swoje konto w SizeHub"
content_path = "./supabase/templates/confirmation.html"

[auth.email.template.recovery]
subject = "Resetowanie hasła - SizeHub"
content_path = "./supabase/templates/recovery.html"
